---
bundler_args: --without development
language: ruby
cache: bundler
rvm:
  - 2.2.0
sudo: false
before_script:
  - mysql -e 'create database elmo_test;'
  - "for f in $(find -name '*.example'); do cp \"$f\" \"${f%.example}\"; done"
  - "sed -ri 's/user: elmo/user: travis/; /password:/d' config/database.yml"
  - bundle exec rake ts:index ts:start db:setup
script: bundle exec rake
env:
  global:
    # Set reCAPTCHA keys to dummy values
    - RECAPTCHA_PUBLIC_KEY=6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
    - RECAPTCHA_PRIVATE_KEY=6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx
