development:
  adapter: mysql
  database: cceom_cc
  host: localhost
  username: cceom_cc
  password: tickleME
  
test:
  adapter: mysql
  database: cceom_cc_t
  host: localhost
  username: cceom_cc_t
  password: tickleME

production:
  adapter: mysql
  database: cceom_cc_sb
  host: localhost
  username: cceom_cc_sb
  password: 19c0bb8b
